import type { Anime } from "./types";

export const FALLBACK_MOVIES: Anime[] = [
  {
    id: 21519,
    idMal: 32281,
    title: {
      english: "Your Name.",
      romaji: "Kimi no Na wa.",
      native: "君の名は。",
    },
    coverImage: {
      large: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx21519-9r81k45p7GqS.png",
      extraLarge: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21519-9r81k45p7GqS.png",
      color: "#e45f2b",
    },
    bannerImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21519-1aym6tTknL1i.jpg",
    description: "Mitsuha Miyamizu, a high school girl living in the town of Itomori, is fed up with her rural life. Meanwhile in Tokyo, Taki Tachibana lives a busy life as a high school student while juggling his part-time job. One day, Mitsuha awakens in a room that is not her own and finds herself in the body of an unfamiliar boy in Tokyo.",
    episodes: 1,
    duration: 106,
    genres: ["Drama", "Romance", "Supernatural"],
    averageScore: 89,
    popularity: 450000,
    format: "MOVIE",
    status: "FINISHED",
    seasonYear: 2016,
  },
  {
    id: 199,
    idMal: 199,
    title: {
      english: "Spirited Away",
      romaji: "Sen to Chihiro no Kamikakushi",
      native: "千と千尋の神隠し",
    },
    coverImage: {
      large: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx199-m1L9kwhgXyL1.jpg",
      extraLarge: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx199-m1L9kwhgXyL1.jpg",
      color: "#e4402b",
    },
    bannerImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/199-rV30zQ2Qy0Fw.jpg",
    description: "Chihiro, a sullen ten-year-old girl, wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts. After her parents are magically transformed, Chihiro must work in a mysterious bathhouse to survive and find a way back home.",
    episodes: 1,
    duration: 125,
    genres: ["Adventure", "Drama", "Fantasy", "Supernatural"],
    averageScore: 88,
    popularity: 380000,
    format: "MOVIE",
    status: "FINISHED",
    seasonYear: 2001,
  },
  {
    id: 20954,
    idMal: 28851,
    title: {
      english: "A Silent Voice",
      romaji: "Koe no Katachi",
      native: "聲の形",
    },
    coverImage: {
      large: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx20954-UMb64TqPtBuh.jpg",
      extraLarge: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20954-UMb64TqPtBuh.jpg",
      color: "#5b84c4",
    },
    bannerImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20954-o2xK5gRptcsl.jpg",
    description: "After transferring into a new school, a deaf girl, Shouko Nishimiya, is bullied by the popular Shouya Ishida. Years later, haunted by guilt, Shouya sets out on a journey of redemption to make amends.",
    episodes: 1,
    duration: 130,
    genres: ["Drama", "Romance", "Slice of Life"],
    averageScore: 88,
    popularity: 420000,
    format: "MOVIE",
    status: "FINISHED",
    seasonYear: 2016,
  },
  {
    id: 112151,
    idMal: 40456,
    title: {
      english: "Demon Slayer: Kimetsu no Yaiba - The Movie: Mugen Train",
      romaji: "Kimetsu no Yaiba Movie: Mugen Ressha-hen",
      native: "劇場版「鬼滅の刃」無限列車編",
    },
    coverImage: {
      large: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx112151-txh1wQ1Jq9M0.jpg",
      extraLarge: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx112151-txh1wQ1Jq9M0.jpg",
      color: "#e43d2b",
    },
    bannerImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/112151-b0K0nL5oQyH2.jpg",
    description: "Tanjiro, Zenitsu, and Inosuke board the Infinity Train to investigate the mysterious disappearance of over forty passengers, joined by the mighty Flame Hashira, Kyojuro Rengoku.",
    episodes: 1,
    duration: 117,
    genres: ["Action", "Adventure", "Fantasy", "Supernatural"],
    averageScore: 86,
    popularity: 390000,
    format: "MOVIE",
    status: "FINISHED",
    seasonYear: 2020,
  },
  {
    id: 131573,
    idMal: 48561,
    title: {
      english: "Jujutsu Kaisen 0",
      romaji: "Jujutsu Kaisen 0",
      native: "劇場版 呪術廻戦 0",
    },
    coverImage: {
      large: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx131573-0wQ1x1d7c3u8.jpg",
      extraLarge: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx131573-0wQ1x1d7c3u8.jpg",
      color: "#303f9f",
    },
    bannerImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/131573-5Yx3p0lM8o2n.jpg",
    description: "Yuta Okkotsu is a nervous high school student who is suffering from a serious problem—his childhood friend Rika has turned into a curse and won't leave him alone. Satoru Gojo enrolls Yuta in Jujutsu High to help control her powers.",
    episodes: 1,
    duration: 105,
    genres: ["Action", "Fantasy", "Supernatural"],
    averageScore: 84,
    popularity: 350000,
    format: "MOVIE",
    status: "FINISHED",
    seasonYear: 2021,
  },
  {
    id: 142853,
    idMal: 50594,
    title: {
      english: "Suzume",
      romaji: "Suzume no Tojimari",
      native: "すずめの戸締まり",
    },
    coverImage: {
      large: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx142853-xP8Nq0wQeX9G.jpg",
      extraLarge: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx142853-xP8Nq0wQeX9G.jpg",
      color: "#3878b2",
    },
    bannerImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/142853-2F4g7r9wT5nL.jpg",
    description: "17-year-old Suzume discovers a mysterious door in the ruins of Kyushu. When other doors begin opening across Japan, unleashing devastation, Suzume embarks on a journey to close and lock them.",
    episodes: 1,
    duration: 121,
    genres: ["Adventure", "Fantasy", "Mystery", "Supernatural"],
    averageScore: 83,
    popularity: 280000,
    format: "MOVIE",
    status: "FINISHED",
    seasonYear: 2022,
  },
  {
    id: 106286,
    idMal: 38826,
    title: {
      english: "Weathering With You",
      romaji: "Tenki no Ko",
      native: "天気の子",
    },
    coverImage: {
      large: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx106286-9m2G8u1o4jK7.jpg",
      extraLarge: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx106286-9m2G8u1o4jK7.jpg",
      color: "#2880b9",
    },
    bannerImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/106286-7t5w2q9l3p1o.jpg",
    description: "High school freshman Hodaka runs away to Tokyo and falls on hard times until he lands a job at an occult magazine. He then meets Hina, an orphan girl who possesses the wondrous ability to stop the rain and clear the sky.",
    episodes: 1,
    duration: 112,
    genres: ["Drama", "Fantasy", "Romance", "Slice of Life"],
    averageScore: 82,
    popularity: 320000,
    format: "MOVIE",
    status: "FINISHED",
    seasonYear: 2019,
  },
  {
    id: 431,
    idMal: 431,
    title: {
      english: "Howl's Moving Castle",
      romaji: "Howl no Ugoku Shiro",
      native: "ハウルの動く城",
    },
    coverImage: {
      large: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx431-R5bJ9s3x2p1k.jpg",
      extraLarge: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx431-R5bJ9s3x2p1k.jpg",
      color: "#b4642e",
    },
    bannerImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/431-8p9q2r3t4y5u.jpg",
    description: "When an unconfident young woman named Sophie is cursed with an old body by a spiteful witch, her only chance of breaking the spell lies with a self-indulgent yet insecure young wizard and his companions in his legged, walking castle.",
    episodes: 1,
    duration: 119,
    genres: ["Adventure", "Drama", "Fantasy", "Romance"],
    averageScore: 87,
    popularity: 350000,
    format: "MOVIE",
    status: "FINISHED",
    seasonYear: 2004,
  },
];

export const FALLBACK_SERIES: Anime[] = [
  {
    id: 151807,
    idMal: 52299,
    title: {
      english: "Solo Leveling",
      romaji: "Ore dake Level Up na Ken",
      native: "俺だけレベルアップな件",
    },
    coverImage: {
      large: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx151807-m1E2X4g5p6r8.jpg",
      extraLarge: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx151807-m1E2X4g5p6r8.jpg",
      color: "#2962ff",
    },
    bannerImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/151807-g1h2j3k4l5m6.jpg",
    description: "In a world where hunters with supernatural powers battle deadly monsters, Sung Jinwoo, known as the 'Weakest Hunter of All Mankind,' is brutally slaughtered in a double dungeon. When he awakens, a mysterious quest window appears before his eyes.",
    episodes: 12,
    duration: 24,
    genres: ["Action", "Adventure", "Fantasy"],
    averageScore: 84,
    popularity: 380000,
    format: "TV",
    status: "FINISHED",
    seasonYear: 2024,
  },
  {
    id: 154587,
    idMal: 52991,
    title: {
      english: "Frieren: Beyond Journey's End",
      romaji: "Sousou no Frieren",
      native: "葬送のフリーレン",
    },
    coverImage: {
      large: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx154587-n2o3p4q5r6s7.jpg",
      extraLarge: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx154587-n2o3p4q5r6s7.jpg",
      color: "#64b5f6",
    },
    bannerImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/154587-8q9w0e1r2t3y.jpg",
    description: "The Demon King has been defeated, and the victorious hero party returns home before disbanding. The four—mage Frieren, hero Himmel, priest Heiter, and warrior Eisen—reminisce about their decade-long journey. But for an elf with a millennia-long lifespan, the passing of human life brings a profound realization.",
    episodes: 28,
    duration: 24,
    genres: ["Adventure", "Drama", "Fantasy"],
    averageScore: 92,
    popularity: 420000,
    format: "TV",
    status: "FINISHED",
    seasonYear: 2023,
  },
  {
    id: 16498,
    idMal: 16498,
    title: {
      english: "Attack on Titan",
      romaji: "Shingeki no Kyojin",
      native: "進撃の巨人",
    },
    coverImage: {
      large: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx16498-C6FPmWm59CyP.jpg",
      extraLarge: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx16498-C6FPmWm59CyP.jpg",
      color: "#8a2b2b",
    },
    bannerImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/16498-8jpFCOcDmneX.jpg",
    description: "Centuries ago, mankind was slaughtered to near extinction by monstrous humanoid creatures called Titans, forcing humans to hide in fear behind enormous concentric walls. After a colossal Titan breaches the outer defense, Eren Yeager vows to cleanse the earth of every giant.",
    episodes: 25,
    duration: 24,
    genres: ["Action", "Drama", "Fantasy", "Mystery"],
    averageScore: 86,
    popularity: 650000,
    format: "TV",
    status: "FINISHED",
    seasonYear: 2013,
  },
  {
    id: 113415,
    idMal: 40748,
    title: {
      english: "Jujutsu Kaisen",
      romaji: "Jujutsu Kaisen",
      native: "呪術廻戦",
    },
    coverImage: {
      large: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx113415-bbBWj4pUbSc2.jpg",
      extraLarge: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx113415-bbBWj4pUbSc2.jpg",
      color: "#1e88e5",
    },
    bannerImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/113415-jQGo78V08PL5.jpg",
    description: "Idly indulging in paranormal activities with the Occult Club, high schooler Yuji Itadori spends his days visiting his bedridden grandfather. However, his leisurely lifestyle takes a turn for the bizarre when he unknowingly encounters a cursed item.",
    episodes: 24,
    duration: 24,
    genres: ["Action", "Drama", "Supernatural"],
    averageScore: 86,
    popularity: 580000,
    format: "TV",
    status: "FINISHED",
    seasonYear: 2020,
  },
  {
    id: 101922,
    idMal: 38000,
    title: {
      english: "Demon Slayer: Kimetsu no Yaiba",
      romaji: "Kimetsu no Yaiba",
      native: "鬼滅の刃",
    },
    coverImage: {
      large: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx101922-WBsBl0ClmgLd.jpg",
      extraLarge: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101922-WBsBl0ClmgLd.jpg",
      color: "#e53935",
    },
    bannerImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/101922-YfZhhrXBj5tl.jpg",
    description: "Ever since the death of his father, the burden of supporting the family has fallen upon Tanjiro Kamado's shoulders. One day, after returning home from selling charcoal in a neighboring town, Tanjiro finds his family slaughtered by demons.",
    episodes: 26,
    duration: 24,
    genres: ["Action", "Adventure", "Fantasy", "Supernatural"],
    averageScore: 85,
    popularity: 550000,
    format: "TV",
    status: "FINISHED",
    seasonYear: 2019,
  },
  {
    id: 127230,
    idMal: 44511,
    title: {
      english: "Chainsaw Man",
      romaji: "Chainsaw Man",
      native: "チェンソーマン",
    },
    coverImage: {
      large: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx127230-FloCoGoagTuz.png",
      extraLarge: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx127230-FloCoGoagTuz.png",
      color: "#f57c00",
    },
    bannerImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/127230-6b45yT7b2p7q.jpg",
    description: "Denji has a simple dream—to live a happy and peaceful life, spending time with a girl he likes. This is a far cry from reality, however, as Denji is forced by the yakuza into killing devils in order to pay off his deceased father's crushing debts.",
    episodes: 12,
    duration: 24,
    genres: ["Action", "Drama", "Supernatural"],
    averageScore: 84,
    popularity: 490000,
    format: "TV",
    status: "FINISHED",
    seasonYear: 2022,
  },
];

export const FALLBACK_NEW: Anime[] = [
  {
    id: 176496,
    idMal: 58514,
    title: {
      english: "Solo Leveling Season 2 -Arise from the Shadow-",
      romaji: "Ore dake Level Up na Ken Season 2: Arise from the Shadow",
      native: "俺だけレベルアップな件 Season 2 -Arise from the Shadow-",
    },
    coverImage: {
      large: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx176496-5e2Pq7wL1q8b.jpg",
      extraLarge: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx176496-5e2Pq7wL1q8b.jpg",
      color: "#2962ff",
    },
    bannerImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/176496-m1n2o3p4q5r6.jpg",
    description: "Following his awakening as the Monarch of Shadows, Sung Jinwoo embarks on the next stage of his ascension, facing formidable S-rank gates, high-level monarchs, and global crises.",
    episodes: 13,
    duration: 24,
    genres: ["Action", "Adventure", "Fantasy"],
    averageScore: 87,
    popularity: 290000,
    format: "TV",
    status: "RELEASING",
    seasonYear: 2025,
  },
  {
    id: 171018,
    idMal: 57334,
    title: {
      english: "Dandadan",
      romaji: "Dandadan",
      native: "ダンダダン",
    },
    coverImage: {
      large: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx171018-7s9k2p3l4o5b.jpg",
      extraLarge: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx171018-7s9k2p3l4o5b.jpg",
      color: "#d81b60",
    },
    bannerImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/171018-1a2b3c4d5e6f.jpg",
    description: "Momo Ayase strikes up an unusual friendship with her school's UFO fanatic, whom she nicknames 'Okarun.' Believing in ghosts but not aliens, Momo bets Okarun to visit a haunted spot, while Okarun challenges her to visit an alien abduction site.",
    episodes: 12,
    duration: 24,
    genres: ["Action", "Comedy", "Supernatural"],
    averageScore: 86,
    popularity: 310000,
    format: "TV",
    status: "FINISHED",
    seasonYear: 2024,
  },
  {
    id: 171806,
    idMal: 57524,
    title: {
      english: "Sakamoto Days",
      romaji: "Sakamoto Days",
      native: "SAKAMOTO DAYS",
    },
    coverImage: {
      large: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx171806-3x5k7p9m1n2b.jpg",
      extraLarge: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx171806-3x5k7p9m1n2b.jpg",
      color: "#fbc02d",
    },
    bannerImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/171806-7q8w9e0r1t2y.jpg",
    description: "Taro Sakamoto was the ultimate hitman, feared by all criminals. But one day he fell in love, got married, retired, had a daughter, and gained a few pounds. Now running a neighborhood convenience store, assassins from his past come calling.",
    episodes: 12,
    duration: 24,
    genres: ["Action", "Comedy"],
    averageScore: 82,
    popularity: 220000,
    format: "TV",
    status: "RELEASING",
    seasonYear: 2025,
  },
];
